CREATE TABLE IF NOT EXISTS routing_ip_pools (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  pool_type ENUM('ingress','server_link') NOT NULL,
  server_id INT UNSIGNED NULL,
  server_protocol_id INT UNSIGNED NULL,
  family TINYINT UNSIGNED NOT NULL DEFAULT 4,
  network VARBINARY(16) NOT NULL,
  prefix_length TINYINT UNSIGNED NOT NULL,
  canonical_cidr VARCHAR(64) NOT NULL,
  status ENUM('reserved','active','disabled') NOT NULL DEFAULT 'reserved',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_routing_pool_cidr (family, network, prefix_length),
  KEY idx_routing_pool_server (server_id),
  KEY idx_routing_pool_protocol (server_protocol_id),
  CONSTRAINT fk_routing_pool_server FOREIGN KEY (server_id) REFERENCES vpn_servers(id) ON DELETE CASCADE,
  CONSTRAINT fk_routing_pool_server_protocol FOREIGN KEY (server_protocol_id) REFERENCES server_protocols(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS routing_ingresses (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  server_id INT UNSIGNED NOT NULL,
  server_protocol_id INT UNSIGNED NOT NULL,
  ip_pool_id INT UNSIGNED NULL,
  interface_name VARCHAR(32) NULL,
  wan_interface VARCHAR(32) NULL,
  agent_endpoint VARCHAR(255) NULL,
  agent_port INT UNSIGNED NOT NULL DEFAULT 9443,
  enabled TINYINT(1) NOT NULL DEFAULT 0,
  status ENUM('disabled','pending','active','error') NOT NULL DEFAULT 'disabled',
  desired_version BIGINT UNSIGNED NOT NULL DEFAULT 0,
  applied_version BIGINT UNSIGNED NOT NULL DEFAULT 0,
  desired_hash CHAR(64) NULL,
  applied_hash CHAR(64) NULL,
  last_sync_at TIMESTAMP NULL,
  last_error TEXT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_routing_ingress_protocol (server_protocol_id),
  KEY idx_routing_ingress_server (server_id),
  KEY idx_routing_ingress_pool (ip_pool_id),
  CONSTRAINT fk_routing_ingress_server FOREIGN KEY (server_id) REFERENCES vpn_servers(id) ON DELETE CASCADE,
  CONSTRAINT fk_routing_ingress_server_protocol FOREIGN KEY (server_protocol_id) REFERENCES server_protocols(id) ON DELETE CASCADE,
  CONSTRAINT fk_routing_ingress_pool FOREIGN KEY (ip_pool_id) REFERENCES routing_ip_pools(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
