CREATE TABLE IF NOT EXISTS routing_server_links (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  ingress_id INT UNSIGNED NOT NULL,
  egress_server_id INT UNSIGNED NOT NULL,
  name VARCHAR(255) NOT NULL,
  transport_pool_id INT UNSIGNED NULL,
  transport_network VARCHAR(64) NULL,
  ingress_tunnel_ip VARCHAR(64) NULL,
  egress_tunnel_ip VARCHAR(64) NULL,
  endpoint_host VARCHAR(255) NULL,
  endpoint_port INT UNSIGNED NULL,
  ingress_interface_name VARCHAR(32) NULL,
  egress_interface_name VARCHAR(32) NULL,
  public_keys JSON NULL,
  secret_refs JSON NULL,
  routing_table_id INT UNSIGNED NULL,
  fwmark INT UNSIGNED NULL,
  user_access_mode ENUM('admin_only','user_allowed','disabled') NOT NULL DEFAULT 'admin_only',
  enabled TINYINT(1) NOT NULL DEFAULT 0,
  status ENUM('unknown','provisioning','active','disabled','error') NOT NULL DEFAULT 'unknown',
  health_status ENUM('unknown','healthy','degraded','down','disabled','error') NOT NULL DEFAULT 'unknown',
  last_handshake_at TIMESTAMP NULL,
  last_error TEXT NULL,
  created_by INT UNSIGNED NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_routing_link_ingress (ingress_id),
  KEY idx_routing_link_egress (egress_server_id),
  KEY idx_routing_link_access (user_access_mode),
  CONSTRAINT fk_routing_link_ingress FOREIGN KEY (ingress_id) REFERENCES routing_ingresses(id) ON DELETE CASCADE,
  CONSTRAINT fk_routing_link_egress FOREIGN KEY (egress_server_id) REFERENCES vpn_servers(id) ON DELETE CASCADE,
  CONSTRAINT fk_routing_link_transport_pool FOREIGN KEY (transport_pool_id) REFERENCES routing_ip_pools(id) ON DELETE SET NULL,
  CONSTRAINT fk_routing_link_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
